apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
        role: master
        tier: backend
    spec:
      containers:
      - name: mongo
        image: launcher.gcr.io/google/mongodb3 # or just image: redis
        args:
          - --auth
        volumeMounts:
        - name: data
          mountPath: /data/db
          subPath: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data